version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql:///prod_db
      - JWT_SECRET_KEY=your_secret_key
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prod_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
