CREATE TABLE City (
    id VARCHAR(36) PRIMARY KEY,
    state_id VARCHAR(36) REFERENCES State(id),
    name VARCHAR(128) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
