CREATE TABLE Review (
    id VARCHAR(36) PRIMARY KEY,
    place_id VARCHAR(36) REFERENCES Place(id),
    user_id VARCHAR(36) REFERENCES User(id),
    text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
